"""Reconcile schema with models: columns missing from 001

Revision ID: 82ec97e1bbbd
Revises: 003
Create Date: 2026-07-28 03:07:49.848054
"""
from __future__ import annotations

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision = "004"
down_revision = "003"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "wallet_concentrations",
        sa.Column("asset_id", sa.UUID(), nullable=False),
        sa.Column("timestamp", sa.DateTime(timezone=True), nullable=False),
        sa.Column("top_10_pct", sa.Numeric(precision=6, scale=3), nullable=True),
        sa.Column("top_50_pct", sa.Numeric(precision=6, scale=3), nullable=True),
        sa.Column("top_100_pct", sa.Numeric(precision=6, scale=3), nullable=True),
        sa.Column("top_1000_pct", sa.Numeric(precision=6, scale=3), nullable=True),
        sa.Column("gini_coefficient", sa.Numeric(precision=6, scale=4), nullable=True),
        sa.Column("hhi_score", sa.Numeric(precision=10, scale=4), nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.ForeignKeyConstraint(["asset_id"], ["assets.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_wallet_conc_asset_ts", "wallet_concentrations", ["asset_id", "timestamp"], unique=False
    )
    op.create_index(
        op.f("ix_wallet_concentrations_asset_id"),
        "wallet_concentrations",
        ["asset_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_wallet_concentrations_timestamp"),
        "wallet_concentrations",
        ["timestamp"],
        unique=False,
    )
    op.drop_index(
        op.f("ix_wallet_concentration_asset_timestamp"), table_name="wallet_concentration"
    )
    op.drop_table("wallet_concentration")
    op.add_column("alerts", sa.Column("is_resolved", sa.Boolean(), nullable=False))
    op.add_column("alerts", sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True))
    op.alter_column("alerts", "asset_id", existing_type=sa.UUID(), nullable=False)
    op.alter_column(
        "alerts",
        "threshold_value",
        existing_type=sa.NUMERIC(precision=30, scale=8),
        type_=sa.Numeric(precision=20, scale=6),
        existing_nullable=True,
    )
    op.alter_column(
        "alerts",
        "actual_value",
        existing_type=sa.NUMERIC(precision=30, scale=8),
        type_=sa.Numeric(precision=20, scale=6),
        existing_nullable=True,
    )
    op.create_index("ix_alert_asset_severity", "alerts", ["asset_id", "severity"], unique=False)
    op.create_index("ix_alert_triggered", "alerts", ["triggered_at"], unique=False)
    op.create_index("ix_alert_user_read", "alerts", ["user_id", "is_read"], unique=False)
    op.create_index(op.f("ix_alerts_alert_type"), "alerts", ["alert_type"], unique=False)
    op.create_index(op.f("ix_alerts_is_read"), "alerts", ["is_read"], unique=False)
    op.create_index(op.f("ix_alerts_user_id"), "alerts", ["user_id"], unique=False)
    op.add_column("api_keys", sa.Column("key_prefix", sa.String(length=12), nullable=False))
    op.add_column(
        "api_keys",
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    )
    op.alter_column(
        "api_keys",
        "name",
        existing_type=sa.VARCHAR(length=255),
        type_=sa.String(length=100),
        existing_nullable=False,
    )
    op.alter_column(
        "api_keys",
        "key_hash",
        existing_type=sa.VARCHAR(length=128),
        type_=sa.String(length=64),
        existing_nullable=False,
    )
    op.drop_constraint(op.f("api_keys_key_hash_key"), "api_keys", type_="unique")
    op.drop_index(op.f("ix_api_keys_key_hash"), table_name="api_keys")
    op.create_index(op.f("ix_api_keys_key_hash"), "api_keys", ["key_hash"], unique=True)
    op.create_index(op.f("ix_api_keys_expires_at"), "api_keys", ["expires_at"], unique=False)
    op.create_index(op.f("ix_api_keys_is_active"), "api_keys", ["is_active"], unique=False)
    op.add_column("assets", sa.Column("description", sa.Text(), nullable=True))
    op.add_column("assets", sa.Column("website_url", sa.String(length=512), nullable=True))
    op.add_column("assets", sa.Column("logo_url", sa.String(length=512), nullable=True))
    op.alter_column(
        "assets",
        "symbol",
        existing_type=sa.VARCHAR(length=32),
        type_=sa.String(length=20),
        existing_nullable=False,
    )
    op.alter_column(
        "assets",
        "blockchain",
        existing_type=sa.VARCHAR(length=64),
        type_=sa.String(length=100),
        nullable=True,
    )
    op.alter_column(
        "assets",
        "contract_address",
        existing_type=sa.VARCHAR(length=128),
        type_=sa.String(length=255),
        existing_nullable=True,
    )
    op.alter_column(
        "assets",
        "coingecko_id",
        existing_type=sa.VARCHAR(length=128),
        type_=sa.String(length=255),
        existing_nullable=True,
    )
    op.alter_column(
        "assets",
        "defillama_id",
        existing_type=sa.VARCHAR(length=128),
        type_=sa.String(length=255),
        existing_nullable=True,
    )
    op.alter_column(
        "assets",
        "metadata",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        nullable=True,
        existing_server_default=sa.text("'{}'::jsonb"),
    )
    op.drop_index(op.f("ix_assets_symbol"), table_name="assets")
    op.create_index(op.f("ix_assets_symbol"), "assets", ["symbol"], unique=True)
    op.create_index(op.f("ix_assets_blockchain"), "assets", ["blockchain"], unique=False)
    op.drop_column("assets", "peg_value")
    op.drop_column("assets", "peg_currency")
    op.add_column("audit_logs", sa.Column("error_message", sa.String(length=1024), nullable=True))
    op.alter_column(
        "audit_logs",
        "action",
        existing_type=sa.VARCHAR(length=128),
        type_=sa.String(length=100),
        existing_nullable=False,
    )
    op.alter_column(
        "audit_logs",
        "resource_type",
        existing_type=sa.VARCHAR(length=64),
        type_=sa.String(length=100),
        nullable=False,
    )
    op.alter_column(
        "audit_logs",
        "resource_id",
        existing_type=sa.VARCHAR(length=128),
        type_=sa.String(length=255),
        existing_nullable=True,
    )
    op.alter_column(
        "audit_logs",
        "details",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        nullable=True,
        existing_server_default=sa.text("'{}'::jsonb"),
    )
    op.create_index(
        op.f("ix_audit_logs_resource_type"), "audit_logs", ["resource_type"], unique=False
    )
    op.create_index(
        "ix_audit_resource", "audit_logs", ["resource_type", "resource_id"], unique=False
    )
    op.create_index("ix_audit_ts", "audit_logs", ["timestamp"], unique=False)
    op.create_index("ix_audit_user_ts", "audit_logs", ["user_id", "timestamp"], unique=False)
    op.add_column(
        "blockchain_metrics",
        sa.Column("burned_supply", sa.Numeric(precision=30, scale=8), nullable=True),
    )
    op.add_column(
        "blockchain_metrics", sa.Column("new_addresses_24h", sa.BigInteger(), nullable=True)
    )
    op.add_column(
        "blockchain_metrics", sa.Column("transfer_count_24h", sa.BigInteger(), nullable=True)
    )
    op.alter_column(
        "blockchain_metrics",
        "avg_transfer_size",
        existing_type=sa.NUMERIC(precision=30, scale=8),
        type_=sa.Numeric(precision=20, scale=4),
        existing_nullable=True,
    )
    op.drop_index(op.f("ix_blockchain_metrics_asset_timestamp"), table_name="blockchain_metrics")
    op.create_index(
        "ix_blockchain_metric_asset_ts",
        "blockchain_metrics",
        ["asset_id", "timestamp"],
        unique=False,
    )
    op.create_index(
        op.f("ix_blockchain_metrics_asset_id"), "blockchain_metrics", ["asset_id"], unique=False
    )
    op.create_index(
        op.f("ix_blockchain_metrics_timestamp"), "blockchain_metrics", ["timestamp"], unique=False
    )
    op.add_column(
        "liquidity_metrics",
        sa.Column("total_liquidity_usd", sa.Numeric(precision=30, scale=2), nullable=True),
    )
    op.add_column(
        "liquidity_metrics",
        sa.Column("slippage_5pct", sa.Numeric(precision=10, scale=4), nullable=True),
    )
    op.add_column(
        "liquidity_metrics",
        sa.Column("depth_1pct_usd", sa.Numeric(precision=20, scale=2), nullable=True),
    )
    op.add_column(
        "liquidity_metrics",
        sa.Column("depth_2pct_usd", sa.Numeric(precision=20, scale=2), nullable=True),
    )
    op.alter_column(
        "liquidity_metrics",
        "slippage_1pct",
        existing_type=sa.NUMERIC(precision=10, scale=6),
        type_=sa.Numeric(precision=10, scale=4),
        existing_nullable=True,
    )
    op.alter_column(
        "liquidity_metrics",
        "slippage_2pct",
        existing_type=sa.NUMERIC(precision=10, scale=6),
        type_=sa.Numeric(precision=10, scale=4),
        existing_nullable=True,
    )
    op.alter_column(
        "liquidity_metrics",
        "top_venues",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        nullable=True,
        existing_server_default=sa.text("'[]'::jsonb"),
    )
    op.drop_index(op.f("ix_liquidity_metrics_asset_timestamp"), table_name="liquidity_metrics")
    op.create_index(
        "ix_liquidity_asset_ts", "liquidity_metrics", ["asset_id", "timestamp"], unique=False
    )
    op.create_index(
        op.f("ix_liquidity_metrics_asset_id"), "liquidity_metrics", ["asset_id"], unique=False
    )
    op.create_index(
        op.f("ix_liquidity_metrics_timestamp"), "liquidity_metrics", ["timestamp"], unique=False
    )
    op.add_column(
        "market_data", sa.Column("price_open", sa.Numeric(precision=24, scale=8), nullable=True)
    )
    op.add_column(
        "market_data", sa.Column("price_high", sa.Numeric(precision=24, scale=8), nullable=True)
    )
    op.add_column(
        "market_data", sa.Column("price_low", sa.Numeric(precision=24, scale=8), nullable=True)
    )
    op.add_column(
        "market_data", sa.Column("price_close", sa.Numeric(precision=24, scale=8), nullable=True)
    )
    op.add_column(
        "market_data", sa.Column("peg_target", sa.Numeric(precision=10, scale=6), nullable=True)
    )
    op.add_column(
        "market_data",
        sa.Column("liquidity_depth_5pct", sa.Numeric(precision=20, scale=2), nullable=True),
    )
    op.add_column(
        "market_data",
        sa.Column("bid_ask_spread_bps", sa.Numeric(precision=10, scale=4), nullable=True),
    )
    op.add_column("market_data", sa.Column("market_cap_rank", sa.BigInteger(), nullable=True))
    op.alter_column(
        "market_data",
        "price_usd",
        existing_type=sa.NUMERIC(precision=30, scale=10),
        type_=sa.Numeric(precision=24, scale=8),
        nullable=True,
    )
    op.alter_column(
        "market_data",
        "liquidity_depth_1pct",
        existing_type=sa.NUMERIC(precision=30, scale=2),
        type_=sa.Numeric(precision=20, scale=2),
        existing_nullable=True,
    )
    op.alter_column(
        "market_data",
        "liquidity_depth_2pct",
        existing_type=sa.NUMERIC(precision=30, scale=2),
        type_=sa.Numeric(precision=20, scale=2),
        existing_nullable=True,
    )
    op.drop_index(op.f("ix_market_data_asset_timestamp"), table_name="market_data")
    op.create_index(op.f("ix_market_data_asset_id"), "market_data", ["asset_id"], unique=False)
    op.create_index(
        "ix_market_data_asset_ts", "market_data", ["asset_id", "timestamp"], unique=False
    )
    op.create_index(op.f("ix_market_data_timestamp"), "market_data", ["timestamp"], unique=False)
    op.create_index("ix_market_data_ts_desc", "market_data", ["timestamp"], unique=False)
    op.drop_column("market_data", "source")
    op.add_column(
        "reserve_attestations", sa.Column("attester_type", sa.String(length=100), nullable=True)
    )
    op.add_column(
        "reserve_attestations",
        sa.Column("total_liabilities_usd", sa.Numeric(precision=30, scale=2), nullable=True),
    )
    op.add_column(
        "reserve_attestations", sa.Column("report_hash", sa.String(length=128), nullable=True)
    )
    op.add_column("reserve_attestations", sa.Column("verification_notes", sa.Text(), nullable=True))
    op.add_column(
        "reserve_attestations",
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    )
    op.alter_column(
        "reserve_attestations",
        "collateralization_ratio",
        existing_type=sa.NUMERIC(precision=10, scale=6),
        type_=sa.Numeric(precision=8, scale=4),
        nullable=True,
    )
    op.alter_column(
        "reserve_attestations",
        "report_url",
        existing_type=sa.VARCHAR(length=2048),
        type_=sa.String(length=1024),
        existing_nullable=True,
    )
    op.drop_index(op.f("ix_reserve_attestations_asset_date"), table_name="reserve_attestations")
    op.create_index(
        "ix_reserve_asset_date",
        "reserve_attestations",
        ["asset_id", "attestation_date"],
        unique=False,
    )
    op.create_index(
        op.f("ix_reserve_attestations_asset_id"), "reserve_attestations", ["asset_id"], unique=False
    )
    op.alter_column(
        "risk_scores",
        "confidence",
        existing_type=sa.NUMERIC(precision=5, scale=4),
        type_=sa.Numeric(precision=4, scale=3),
        existing_nullable=False,
        existing_server_default=sa.text("1.0"),
    )
    op.drop_index(op.f("ix_risk_scores_asset_date"), table_name="risk_scores")
    op.drop_index(op.f("ix_risk_scores_date_score"), table_name="risk_scores")
    op.drop_constraint(op.f("uq_risk_score_asset_date"), "risk_scores", type_="unique")
    op.create_index(
        "ix_risk_score_asset_date", "risk_scores", ["asset_id", "score_date"], unique=False
    )
    op.create_index(
        "ix_risk_score_date_score", "risk_scores", ["score_date", "overall_score"], unique=False
    )
    op.create_index(op.f("ix_risk_scores_asset_id"), "risk_scores", ["asset_id"], unique=False)
    op.create_index(op.f("ix_risk_scores_risk_band"), "risk_scores", ["risk_band"], unique=False)
    op.alter_column(
        "users",
        "email",
        existing_type=sa.VARCHAR(length=255),
        type_=sa.String(length=320),
        existing_nullable=False,
    )
    op.drop_constraint(op.f("users_email_key"), "users", type_="unique")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_index(op.f("ix_users_role"), "users", ["role"], unique=False)
    op.add_column("watchlists", sa.Column("description", sa.String(length=512), nullable=True))
    op.add_column("watchlists", sa.Column("is_default", sa.Boolean(), nullable=False))
    op.alter_column(
        "watchlists",
        "name",
        existing_type=sa.VARCHAR(length=255),
        type_=sa.String(length=100),
        existing_nullable=False,
    )
    op.create_unique_constraint("uq_watchlist_user_name", "watchlists", ["user_id", "name"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uq_watchlist_user_name", "watchlists", type_="unique")
    op.alter_column(
        "watchlists",
        "name",
        existing_type=sa.String(length=100),
        type_=sa.VARCHAR(length=255),
        existing_nullable=False,
    )
    op.drop_column("watchlists", "is_default")
    op.drop_column("watchlists", "description")
    op.drop_index(op.f("ix_users_role"), table_name="users")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=False)
    op.create_unique_constraint(
        op.f("users_email_key"), "users", ["email"], postgresql_nulls_not_distinct=False
    )
    op.alter_column(
        "users",
        "email",
        existing_type=sa.String(length=320),
        type_=sa.VARCHAR(length=255),
        existing_nullable=False,
    )
    op.drop_index(op.f("ix_risk_scores_risk_band"), table_name="risk_scores")
    op.drop_index(op.f("ix_risk_scores_asset_id"), table_name="risk_scores")
    op.drop_index("ix_risk_score_date_score", table_name="risk_scores")
    op.drop_index("ix_risk_score_asset_date", table_name="risk_scores")
    op.create_unique_constraint(
        op.f("uq_risk_score_asset_date"),
        "risk_scores",
        ["asset_id", "score_date"],
        postgresql_nulls_not_distinct=False,
    )
    op.create_index(
        op.f("ix_risk_scores_date_score"),
        "risk_scores",
        ["score_date", "overall_score"],
        unique=False,
    )
    op.create_index(
        op.f("ix_risk_scores_asset_date"), "risk_scores", ["asset_id", "score_date"], unique=False
    )
    op.alter_column(
        "risk_scores",
        "confidence",
        existing_type=sa.Numeric(precision=4, scale=3),
        type_=sa.NUMERIC(precision=5, scale=4),
        existing_nullable=False,
        existing_server_default=sa.text("1.0"),
    )
    op.drop_index(op.f("ix_reserve_attestations_asset_id"), table_name="reserve_attestations")
    op.drop_index("ix_reserve_asset_date", table_name="reserve_attestations")
    op.create_index(
        op.f("ix_reserve_attestations_asset_date"),
        "reserve_attestations",
        ["asset_id", "attestation_date"],
        unique=False,
    )
    op.alter_column(
        "reserve_attestations",
        "report_url",
        existing_type=sa.String(length=1024),
        type_=sa.VARCHAR(length=2048),
        existing_nullable=True,
    )
    op.alter_column(
        "reserve_attestations",
        "collateralization_ratio",
        existing_type=sa.Numeric(precision=8, scale=4),
        type_=sa.NUMERIC(precision=10, scale=6),
        nullable=False,
    )
    op.drop_column("reserve_attestations", "updated_at")
    op.drop_column("reserve_attestations", "verification_notes")
    op.drop_column("reserve_attestations", "report_hash")
    op.drop_column("reserve_attestations", "total_liabilities_usd")
    op.drop_column("reserve_attestations", "attester_type")
    op.add_column(
        "market_data",
        sa.Column(
            "source",
            sa.VARCHAR(length=64),
            server_default=sa.text("'coingecko'::character varying"),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.drop_index("ix_market_data_ts_desc", table_name="market_data")
    op.drop_index(op.f("ix_market_data_timestamp"), table_name="market_data")
    op.drop_index("ix_market_data_asset_ts", table_name="market_data")
    op.drop_index(op.f("ix_market_data_asset_id"), table_name="market_data")
    op.create_index(
        op.f("ix_market_data_asset_timestamp"),
        "market_data",
        ["asset_id", "timestamp"],
        unique=False,
    )
    op.alter_column(
        "market_data",
        "liquidity_depth_2pct",
        existing_type=sa.Numeric(precision=20, scale=2),
        type_=sa.NUMERIC(precision=30, scale=2),
        existing_nullable=True,
    )
    op.alter_column(
        "market_data",
        "liquidity_depth_1pct",
        existing_type=sa.Numeric(precision=20, scale=2),
        type_=sa.NUMERIC(precision=30, scale=2),
        existing_nullable=True,
    )
    op.alter_column(
        "market_data",
        "price_usd",
        existing_type=sa.Numeric(precision=24, scale=8),
        type_=sa.NUMERIC(precision=30, scale=10),
        nullable=False,
    )
    op.drop_column("market_data", "market_cap_rank")
    op.drop_column("market_data", "bid_ask_spread_bps")
    op.drop_column("market_data", "liquidity_depth_5pct")
    op.drop_column("market_data", "peg_target")
    op.drop_column("market_data", "price_close")
    op.drop_column("market_data", "price_low")
    op.drop_column("market_data", "price_high")
    op.drop_column("market_data", "price_open")
    op.drop_index(op.f("ix_liquidity_metrics_timestamp"), table_name="liquidity_metrics")
    op.drop_index(op.f("ix_liquidity_metrics_asset_id"), table_name="liquidity_metrics")
    op.drop_index("ix_liquidity_asset_ts", table_name="liquidity_metrics")
    op.create_index(
        op.f("ix_liquidity_metrics_asset_timestamp"),
        "liquidity_metrics",
        ["asset_id", "timestamp"],
        unique=False,
    )
    op.alter_column(
        "liquidity_metrics",
        "top_venues",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        nullable=False,
        existing_server_default=sa.text("'[]'::jsonb"),
    )
    op.alter_column(
        "liquidity_metrics",
        "slippage_2pct",
        existing_type=sa.Numeric(precision=10, scale=4),
        type_=sa.NUMERIC(precision=10, scale=6),
        existing_nullable=True,
    )
    op.alter_column(
        "liquidity_metrics",
        "slippage_1pct",
        existing_type=sa.Numeric(precision=10, scale=4),
        type_=sa.NUMERIC(precision=10, scale=6),
        existing_nullable=True,
    )
    op.drop_column("liquidity_metrics", "depth_2pct_usd")
    op.drop_column("liquidity_metrics", "depth_1pct_usd")
    op.drop_column("liquidity_metrics", "slippage_5pct")
    op.drop_column("liquidity_metrics", "total_liquidity_usd")
    op.drop_index(op.f("ix_blockchain_metrics_timestamp"), table_name="blockchain_metrics")
    op.drop_index(op.f("ix_blockchain_metrics_asset_id"), table_name="blockchain_metrics")
    op.drop_index("ix_blockchain_metric_asset_ts", table_name="blockchain_metrics")
    op.create_index(
        op.f("ix_blockchain_metrics_asset_timestamp"),
        "blockchain_metrics",
        ["asset_id", "timestamp"],
        unique=False,
    )
    op.alter_column(
        "blockchain_metrics",
        "avg_transfer_size",
        existing_type=sa.Numeric(precision=20, scale=4),
        type_=sa.NUMERIC(precision=30, scale=8),
        existing_nullable=True,
    )
    op.drop_column("blockchain_metrics", "transfer_count_24h")
    op.drop_column("blockchain_metrics", "new_addresses_24h")
    op.drop_column("blockchain_metrics", "burned_supply")
    op.drop_index("ix_audit_user_ts", table_name="audit_logs")
    op.drop_index("ix_audit_ts", table_name="audit_logs")
    op.drop_index("ix_audit_resource", table_name="audit_logs")
    op.drop_index(op.f("ix_audit_logs_resource_type"), table_name="audit_logs")
    op.alter_column(
        "audit_logs",
        "details",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        nullable=False,
        existing_server_default=sa.text("'{}'::jsonb"),
    )
    op.alter_column(
        "audit_logs",
        "resource_id",
        existing_type=sa.String(length=255),
        type_=sa.VARCHAR(length=128),
        existing_nullable=True,
    )
    op.alter_column(
        "audit_logs",
        "resource_type",
        existing_type=sa.String(length=100),
        type_=sa.VARCHAR(length=64),
        nullable=True,
    )
    op.alter_column(
        "audit_logs",
        "action",
        existing_type=sa.String(length=100),
        type_=sa.VARCHAR(length=128),
        existing_nullable=False,
    )
    op.drop_column("audit_logs", "error_message")
    op.add_column(
        "assets",
        sa.Column(
            "peg_currency",
            sa.VARCHAR(length=8),
            server_default=sa.text("'USD'::character varying"),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.add_column(
        "assets",
        sa.Column(
            "peg_value",
            sa.NUMERIC(precision=20, scale=8),
            server_default=sa.text("1.0"),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.drop_index(op.f("ix_assets_blockchain"), table_name="assets")
    op.drop_index(op.f("ix_assets_symbol"), table_name="assets")
    op.create_index(op.f("ix_assets_symbol"), "assets", ["symbol"], unique=False)
    op.alter_column(
        "assets",
        "metadata",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        nullable=False,
        existing_server_default=sa.text("'{}'::jsonb"),
    )
    op.alter_column(
        "assets",
        "defillama_id",
        existing_type=sa.String(length=255),
        type_=sa.VARCHAR(length=128),
        existing_nullable=True,
    )
    op.alter_column(
        "assets",
        "coingecko_id",
        existing_type=sa.String(length=255),
        type_=sa.VARCHAR(length=128),
        existing_nullable=True,
    )
    op.alter_column(
        "assets",
        "contract_address",
        existing_type=sa.String(length=255),
        type_=sa.VARCHAR(length=128),
        existing_nullable=True,
    )
    op.alter_column(
        "assets",
        "blockchain",
        existing_type=sa.String(length=100),
        type_=sa.VARCHAR(length=64),
        nullable=False,
    )
    op.alter_column(
        "assets",
        "symbol",
        existing_type=sa.String(length=20),
        type_=sa.VARCHAR(length=32),
        existing_nullable=False,
    )
    op.drop_column("assets", "logo_url")
    op.drop_column("assets", "website_url")
    op.drop_column("assets", "description")
    op.drop_index(op.f("ix_api_keys_is_active"), table_name="api_keys")
    op.drop_index(op.f("ix_api_keys_expires_at"), table_name="api_keys")
    op.drop_index(op.f("ix_api_keys_key_hash"), table_name="api_keys")
    op.create_index(op.f("ix_api_keys_key_hash"), "api_keys", ["key_hash"], unique=False)
    op.create_unique_constraint(
        op.f("api_keys_key_hash_key"), "api_keys", ["key_hash"], postgresql_nulls_not_distinct=False
    )
    op.alter_column(
        "api_keys",
        "key_hash",
        existing_type=sa.String(length=64),
        type_=sa.VARCHAR(length=128),
        existing_nullable=False,
    )
    op.alter_column(
        "api_keys",
        "name",
        existing_type=sa.String(length=100),
        type_=sa.VARCHAR(length=255),
        existing_nullable=False,
    )
    op.drop_column("api_keys", "updated_at")
    op.drop_column("api_keys", "key_prefix")
    op.drop_index(op.f("ix_alerts_user_id"), table_name="alerts")
    op.drop_index(op.f("ix_alerts_is_read"), table_name="alerts")
    op.drop_index(op.f("ix_alerts_alert_type"), table_name="alerts")
    op.drop_index("ix_alert_user_read", table_name="alerts")
    op.drop_index("ix_alert_triggered", table_name="alerts")
    op.drop_index("ix_alert_asset_severity", table_name="alerts")
    op.alter_column(
        "alerts",
        "actual_value",
        existing_type=sa.Numeric(precision=20, scale=6),
        type_=sa.NUMERIC(precision=30, scale=8),
        existing_nullable=True,
    )
    op.alter_column(
        "alerts",
        "threshold_value",
        existing_type=sa.Numeric(precision=20, scale=6),
        type_=sa.NUMERIC(precision=30, scale=8),
        existing_nullable=True,
    )
    op.alter_column("alerts", "asset_id", existing_type=sa.UUID(), nullable=True)
    op.drop_column("alerts", "resolved_at")
    op.drop_column("alerts", "is_resolved")
    op.create_table(
        "wallet_concentration",
        sa.Column(
            "id",
            sa.UUID(),
            server_default=sa.text("gen_random_uuid()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("asset_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column(
            "timestamp", postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False
        ),
        sa.Column(
            "top_10_pct", sa.NUMERIC(precision=5, scale=4), autoincrement=False, nullable=True
        ),
        sa.Column(
            "top_50_pct", sa.NUMERIC(precision=5, scale=4), autoincrement=False, nullable=True
        ),
        sa.Column(
            "top_100_pct", sa.NUMERIC(precision=5, scale=4), autoincrement=False, nullable=True
        ),
        sa.Column(
            "gini_coefficient", sa.NUMERIC(precision=5, scale=4), autoincrement=False, nullable=True
        ),
        sa.Column(
            "hhi_score", sa.NUMERIC(precision=10, scale=4), autoincrement=False, nullable=True
        ),
        sa.ForeignKeyConstraint(
            ["asset_id"],
            ["assets.id"],
            name=op.f("wallet_concentration_asset_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", "timestamp", name=op.f("wallet_concentration_pkey")),
    )
    op.create_index(
        op.f("ix_wallet_concentration_asset_timestamp"),
        "wallet_concentration",
        ["asset_id", "timestamp"],
        unique=False,
    )
    op.drop_index(op.f("ix_wallet_concentrations_timestamp"), table_name="wallet_concentrations")
    op.drop_index(op.f("ix_wallet_concentrations_asset_id"), table_name="wallet_concentrations")
    op.drop_index("ix_wallet_conc_asset_ts", table_name="wallet_concentrations")
    op.drop_table("wallet_concentrations")
    # ### end Alembic commands ###
